export const profileActionTypes = {
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILES: 'GET_PROFILES',
    PROFILE_ERROR: 'PROFILE_ERROR',
    GET_REPOS: 'GET_REPOS',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    CLEAR_PROFILE: 'CLEAR_PROFILE'
}